
# = Hibernate datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_cinecoce?serverTimezone=UTC
    username: root
    password: root



  # = JPA configurations
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

# = Logging configurations
logging:
  level:
    root: warn
    org.springframework.web: DEBUG
    org.springframework.security: INFO


# = Port configurations
server:
  port: 9010
